 --1. 他網扣永豐與財金入帳開始時間 ：營業日9:10  
SELECT * FROM PARAMETER WHERE NAME='EDI_WORKTIME_START';

--2. 自網扣永豐入他行開始時間：營業日8:00
SELECT * FROM PARAMETER  WHERE NAME='START_TIME_MMA2HOST';
--3. 他網扣永豐結束時間：營業日15:30
SELECT * FROM PARAMETER  WHERE NAME='HOST_PAYEXT_END_TIME';

--4. 財金入帳結束時間：營業日16:40
SELECT * FROM PARAMETER  WHERE NAME='EDI_WORKTIME_END';
SELECT * FROM PARAMETER  WHERE NAME='EDI_WORKTIME_BUF_END';

--5. 自網扣永豐入他行結束時間：營業日16:30
SELECT * FROM PARAMETER  WHERE NAME='STOP_TIME_MMA2HOST';